fix: pipline and migration files

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -3,26 +3,73 @@ name: PIPELINE
 on:
     push:
         branches:
-            - ref/requirement-changes
+            - main
             - development
-    
-jobs:
-    deploy:
-        runs-on: ubuntu-latest
+            - "feat/**"
+            - "fix/**"
 
+jobs:
+    build_and_test:
+        runs-on: ubuntu-latest
         steps:
             - name: Checkout code
               uses: actions/checkout@v3
 
+            - name: Set up Python
+              uses: actions/setup-python@v4
+              with:
+                  python-version: "3.13"
+
+            - name: Install dependencies
+              run: |
+                  python -m pip install --upgrade pip
+                  pip install -r requirements/dev.txt
+
+            - name: Lint code
+              run: |
+                  flake8 .
+
+            - name: Run tests
+              run: |
+                  pytest --disable-warnings --maxfail=1
+
+    #   docker_build:
+    #     runs-on: ubuntu-latest
+    #     needs: build_and_test
+    #     if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'
+    #     steps:
+    #       - uses: actions/checkout@v3
+    #       - uses: docker/setup-buildx-action@v2
+    #       - uses: docker/login-action@v2
+    #         with:
+    #           username: ${{ secrets.DOCKER_USERNAME }}
+    #           password: ${{ secrets.DOCKER_PASSWORD }}
+    #       - uses: docker/build-push-action@v4
+    #         with:
+    #           context: .
+    #           file: ./Dockerfile
+    #           push: true
+    #           tags: |
+    #             ${{ secrets.DOCKER_USERNAME }}/michot_marefiya_backend:${{ github.ref_name }}
+    #             ${{ secrets.DOCKER_USERNAME }}/michot_marefiya_backend:latest
+
+    deploy:
+        runs-on: ubuntu-latest
+        # needs: docker_build
+        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'
+        steps:
             - name: Deploy via SSH
               uses: appleboy/ssh-action@v1.0.0
               with:
-                  host: ${{ secrets.VPS_HOST }}
-                  username: ${{ secrets.VPS_USER }}
-                  key: ${{ secrets.VPS_SSH_KEY }}
+                  host: ${{ github.ref == 'refs/heads/main' && secrets.VPS_HOST }}
+                  username: ${{ github.ref == 'refs/heads/main' && secrets.VPS_USER }}
+                  key: ${{ github.ref == 'refs/heads/main' && secrets.VPS_SSH_KEY  }}
                   script: |
                       cd ./michot_marefiya_backend
-                      git pull origin development
-                      docker compose down
+                      git pull origin ${{ github.ref_name }}
+                      docker compose -f compose.prod.yaml pull
+                      docker compose -f compose.prod.yaml down
                       docker compose -f compose.prod.yaml up -d --build
-
+                      docker compose exec api python manage.py migrate --noinput
+                      sleep 10
+                      curl -f https://${{ github.ref == 'refs/heads/main' && 'michotmarefia.com'}}/health || (echo "Deployment failed!" && exit 1)
